name: iOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: |
        cd project
        flutter pub get
    
    - name: Build iOS
      run: |
        cd project
        flutter build ios --no-codesign
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: project/build/ios/
        retention-days: 30
